package interfaz;

import javax.swing.JTextField;
import modelo.Cliente;

public class MenuGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuGUI.class.getName());

    public MenuGUI() {
        initComponents();
        //JTextField editor = (JTextField) cmbCliente.getEditor().getEditorComponent(); // Acceder al editor del JComboBox
    }
    
    public javax.swing.JList<String> getListaDeOpciones() {
    return ListaDeOpciones;
    }

    public javax.swing.JPanel getPanelImagenes() {
        return PanelImagenes;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelImagenes = new javax.swing.JPanel();
        pnllNuevoPedido = new javax.swing.JPanel();
        lblNuevoPedido = new javax.swing.JLabel();
        pnlPedidos = new javax.swing.JPanel();
        lblPedidos = new javax.swing.JLabel();
        pnlPagos = new javax.swing.JPanel();
        lblPagos = new javax.swing.JLabel();
        pnlClientes = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        pnlHistorial = new javax.swing.JPanel();
        lblHistorial = new javax.swing.JLabel();
        pnlGanancias = new javax.swing.JPanel();
        lblGanancias = new javax.swing.JLabel();
        NuevoPedidoCRUD = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cmbCliente = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        spnCantidad = new javax.swing.JSpinner();
        cmbTamañoSopa = new javax.swing.JComboBox<>();
        ClientesCRUD = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblClientes = new javax.swing.JTable();
        btnModificarCliente = new javax.swing.JButton();
        btnAgregarCliente = new javax.swing.JButton();
        btnEliminarCliente = new javax.swing.JButton();
        lblTelefonoCliente = new javax.swing.JLabel();
        lblNombreCliente = new javax.swing.JLabel();
        txtNombreCliente = new javax.swing.JTextField();
        txtTelefonoCliente = new javax.swing.JTextField();
        PedidosCRUD = new javax.swing.JPanel();
        PanelMenu = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListaDeOpciones = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setLocationByPlatform(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelImagenes.setLayout(new java.awt.CardLayout());

        pnllNuevoPedido.setLayout(new java.awt.BorderLayout());

        lblNuevoPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/traditional-paraguayan-cornbread-like-dish-cheese-onions-cut-squares-displayed-rustic-wooden-board-image-375596596.png"))); // NOI18N
        pnllNuevoPedido.add(lblNuevoPedido, java.awt.BorderLayout.CENTER);

        PanelImagenes.add(pnllNuevoPedido, "Nuevo Pedido");

        pnlPedidos.setLayout(new java.awt.BorderLayout());

        lblPedidos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Horno.png"))); // NOI18N
        pnlPedidos.add(lblPedidos, java.awt.BorderLayout.CENTER);

        PanelImagenes.add(pnlPedidos, "Pedidos");

        pnlPagos.setLayout(new java.awt.BorderLayout());

        lblPagos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/plata.png"))); // NOI18N
        pnlPagos.add(lblPagos, java.awt.BorderLayout.CENTER);

        PanelImagenes.add(pnlPagos, "Pagos");

        pnlClientes.setLayout(new java.awt.BorderLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/alegres-empresarias-dándose-la-mano-en-la-sala-de-reuniones.png"))); // NOI18N
        pnlClientes.add(jLabel5, java.awt.BorderLayout.CENTER);

        PanelImagenes.add(pnlClientes, "Clientes");

        pnlHistorial.setLayout(new java.awt.BorderLayout());

        lblHistorial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/PapelesEnHDpng.png"))); // NOI18N
        pnlHistorial.add(lblHistorial, java.awt.BorderLayout.CENTER);

        PanelImagenes.add(pnlHistorial, "Historial");

        pnlGanancias.setLayout(new java.awt.BorderLayout());

        lblGanancias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/CajeroHD.png"))); // NOI18N
        pnlGanancias.add(lblGanancias, java.awt.BorderLayout.CENTER);

        PanelImagenes.add(pnlGanancias, "Ganancias");

        jLabel1.setFont(new java.awt.Font("Viner Hand ITC", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("NUEVO PEDIDO");

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel2.setText("Detalles:");

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel3.setText("Cliente");

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel4.setText("Total");

        cmbCliente.setEditable(true);

        jLabel6.setText("Cantidad:");

        jLabel7.setText("Tamaño:");

        cmbTamañoSopa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTamañoSopaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout NuevoPedidoCRUDLayout = new javax.swing.GroupLayout(NuevoPedidoCRUD);
        NuevoPedidoCRUD.setLayout(NuevoPedidoCRUDLayout);
        NuevoPedidoCRUDLayout.setHorizontalGroup(
            NuevoPedidoCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
            .addGroup(NuevoPedidoCRUDLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(NuevoPedidoCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NuevoPedidoCRUDLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(spnCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbTamañoSopa, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(152, 152, 152))
                    .addGroup(NuevoPedidoCRUDLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel4))))
            .addGroup(NuevoPedidoCRUDLayout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addComponent(cmbCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(NuevoPedidoCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(NuevoPedidoCRUDLayout.createSequentialGroup()
                    .addGap(76, 76, 76)
                    .addComponent(jLabel3)
                    .addContainerGap(568, Short.MAX_VALUE)))
        );
        NuevoPedidoCRUDLayout.setVerticalGroup(
            NuevoPedidoCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NuevoPedidoCRUDLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(cmbCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(NuevoPedidoCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NuevoPedidoCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(jLabel7)
                        .addComponent(spnCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cmbTamañoSopa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2))
                .addGap(65, 65, 65)
                .addComponent(jLabel4)
                .addGap(0, 157, Short.MAX_VALUE))
            .addGroup(NuevoPedidoCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(NuevoPedidoCRUDLayout.createSequentialGroup()
                    .addGap(128, 128, 128)
                    .addComponent(jLabel3)
                    .addContainerGap(300, Short.MAX_VALUE)))
        );

        PanelImagenes.add(NuevoPedidoCRUD, "Nuevo Pedido CRUD");

        tblClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Cliente", "Telefono"
            }
        ));
        jScrollPane2.setViewportView(tblClientes);

        btnModificarCliente.setText("Modificar");

        btnAgregarCliente.setText("Agregar");

        btnEliminarCliente.setText("Eliminar");

        lblTelefonoCliente.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lblTelefonoCliente.setText("Telefono:");

        lblNombreCliente.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lblNombreCliente.setText("Nombre:");

        javax.swing.GroupLayout ClientesCRUDLayout = new javax.swing.GroupLayout(ClientesCRUD);
        ClientesCRUD.setLayout(ClientesCRUDLayout);
        ClientesCRUDLayout.setHorizontalGroup(
            ClientesCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ClientesCRUDLayout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addComponent(lblTelefonoCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ClientesCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ClientesCRUDLayout.createSequentialGroup()
                        .addGroup(ClientesCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTelefonoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ClientesCRUDLayout.createSequentialGroup()
                        .addComponent(btnAgregarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnModificarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEliminarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(122, 122, 122))))
            .addGroup(ClientesCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ClientesCRUDLayout.createSequentialGroup()
                    .addGap(48, 48, 48)
                    .addComponent(lblNombreCliente)
                    .addContainerGap(583, Short.MAX_VALUE)))
        );
        ClientesCRUDLayout.setVerticalGroup(
            ClientesCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ClientesCRUDLayout.createSequentialGroup()
                .addGroup(ClientesCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ClientesCRUDLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ClientesCRUDLayout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(txtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addGroup(ClientesCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTelefonoCliente)
                            .addComponent(txtTelefonoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(ClientesCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnModificarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(ClientesCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ClientesCRUDLayout.createSequentialGroup()
                    .addGap(106, 106, 106)
                    .addComponent(lblNombreCliente)
                    .addContainerGap(322, Short.MAX_VALUE)))
        );

        PanelImagenes.add(ClientesCRUD, "ClientesCRUD");

        javax.swing.GroupLayout PedidosCRUDLayout = new javax.swing.GroupLayout(PedidosCRUD);
        PedidosCRUD.setLayout(PedidosCRUDLayout);
        PedidosCRUDLayout.setHorizontalGroup(
            PedidosCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        PedidosCRUDLayout.setVerticalGroup(
            PedidosCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );

        PanelImagenes.add(PedidosCRUD, "PedidosCRUD");

        getContentPane().add(PanelImagenes, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 700, 450));

        PanelMenu.setBackground(new java.awt.Color(204, 51, 0));
        PanelMenu.setLayout(new java.awt.BorderLayout());

        ListaDeOpciones.setBackground(new java.awt.Color(0, 0, 0));
        ListaDeOpciones.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        ListaDeOpciones.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Nuevo Pedido", "Pedidos", "Pagos", "Clientes", "Historial", "Ganancias" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(ListaDeOpciones);

        PanelMenu.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(PanelMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbTamañoSopaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTamañoSopaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbTamañoSopaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(() -> new MenuGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ClientesCRUD;
    private javax.swing.JList<String> ListaDeOpciones;
    private javax.swing.JPanel NuevoPedidoCRUD;
    private javax.swing.JPanel PanelImagenes;
    private javax.swing.JPanel PanelMenu;
    private javax.swing.JPanel PedidosCRUD;
    public javax.swing.JButton btnAgregarCliente;
    public javax.swing.JButton btnEliminarCliente;
    public javax.swing.JButton btnModificarCliente;
    public javax.swing.JComboBox<Cliente> cmbCliente;
    public javax.swing.JComboBox<String> cmbTamañoSopa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblGanancias;
    private javax.swing.JLabel lblHistorial;
    private javax.swing.JLabel lblNombreCliente;
    private javax.swing.JLabel lblNuevoPedido;
    private javax.swing.JLabel lblPagos;
    private javax.swing.JLabel lblPedidos;
    private javax.swing.JLabel lblTelefonoCliente;
    private javax.swing.JPanel pnlClientes;
    private javax.swing.JPanel pnlGanancias;
    private javax.swing.JPanel pnlHistorial;
    private javax.swing.JPanel pnlPagos;
    private javax.swing.JPanel pnlPedidos;
    private javax.swing.JPanel pnllNuevoPedido;
    public javax.swing.JSpinner spnCantidad;
    public javax.swing.JTable tblClientes;
    public javax.swing.JTextField txtNombreCliente;
    public javax.swing.JTextField txtTelefonoCliente;
    // End of variables declaration//GEN-END:variables
}

